# Generated by Django 5.0.6 on 2024-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_experience', models.CharField(max_length=120, verbose_name="titre de la l'expérience")),
                ('description_experience', models.TextField(verbose_name="description de l'expérience")),
                ('date_experience', models.CharField(max_length=50, verbose_name="date de l'expérience")),
                ('location_experience', models.CharField(max_length=100, verbose_name="lieu de l'expérience")),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_formation', models.CharField(max_length=120, verbose_name='titre de la formation')),
                ('description_formation', models.TextField(verbose_name='description de la formation')),
                ('date_formation', models.CharField(max_length=50, verbose_name='date de la formation')),
                ('location_formation', models.CharField(max_length=100, verbose_name='lieu de la formation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hobby', models.CharField(max_length=120, verbose_name='titre du hobbie')),
            ],
            options={
                'verbose_name': 'Hobbie',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_language', models.CharField(max_length=120, verbose_name='titre de la langue')),
                ('niveau_language', models.CharField(choices=[('debutant', 'debutant'), ('intermediaire', 'intermediaire'), ('avance', 'avance')], max_length=120, verbose_name='niveau de la langue choisie')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_Skill', models.CharField(max_length=120, verbose_name='titre de la compétence')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='titre du curriculm')),
                ('lastname', models.CharField(max_length=120, verbose_name='nom du curriculum')),
                ('firstname', models.CharField(blank=True, max_length=120, null=True, verbose_name='prénom du curriculum')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='adresse du curriculum')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='ville du curriculum')),
                ('state', models.CharField(blank=True, max_length=120, null=True, verbose_name='état du curriculum')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='code postal du curriculum')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='téléphone du curriculum')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email du curriculum')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='photo du curriculum')),
                ('motivation', models.TextField(blank=True, null=True, verbose_name='motivation du curriculum')),
                ('is_active', models.BooleanField(default=False, verbose_name='curriculum is active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('experiences', models.ManyToManyField(blank=True, related_name='experiences', to='curriculum.experience')),
                ('formations', models.ManyToManyField(blank=True, related_name='formations', to='curriculum.formation')),
                ('hobbies', models.ManyToManyField(blank=True, related_name='hobbies', to='curriculum.hobby')),
                ('languages', models.ManyToManyField(blank=True, related_name='languages', to='curriculum.language')),
                ('skills', models.ManyToManyField(blank=True, related_name='skills', to='curriculum.skill')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
