# Generated by Django 5.0.6 on 2024-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_experience_info_hobby_info_language_info_skill_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date_experience',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_formation',
        ),
        migrations.AddField(
            model_name='experience',
            name='business',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='école ou entreprise'),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date_of_experience',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de fin de l'expérience"),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date_of_experience',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date de début de l'expérience"),
        ),
        migrations.AddField(
            model_name='formation',
            name='business',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='école ou entreprise'),
        ),
        migrations.AddField(
            model_name='formation',
            name='end_date_of_formation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de fin de la formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='start_date_of_formation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de début de la formation'),
        ),
        migrations.AddField(
            model_name='info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance de la personne'),
        ),
        migrations.AddField(
            model_name='info',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='lieu de naissance de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='adresse de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='firstname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='prénom de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='nom de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='motivation de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='téléphone de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='photo de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='code postal'),
        ),
    ]
