# Generated by Django 5.0.6 on 2024-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_experience_end_date_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='type_of_Contract',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='type de contrat'),
        ),
    ]
